# Activer la protection CSRF sans état pour les formulaires et les connexions/déconnexions
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
