# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# Ce fichier est le point d'entrée pour configurer vos propres services.
# Les fichiers dans le sous-répertoire packages/ configurent vos dépendances.
# Voir aussi : https://symfony.com/doc/current/service_container/import.html

# Placez ici les paramètres qui n'ont pas besoin de changer sur chaque machine où l'application est déployée
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # Configuration par défaut pour les services dans *ce* fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services comme commandes, abonnés d'événements, etc.

    # Rend les classes dans src/ disponibles pour être utilisées comme services
    # Cela crée un service par classe dont l'id est le nom de classe complet
    App\:
        resource: '../src/'

    # Ajoutez plus de définitions de services lorsque une configuration explicite est nécessaire
    # Notez que les dernières définitions *remplacent* toujours les précédentes
